
const STORAGE_KEY="no-kidding-band-manager-v02";
const typeNames={live:"ライブ",studio:"スタジオ",meeting:"ミーティング",recording:"レコーディング",other:"その他"};
const typeStickers={live:"NEXT LIVE",studio:"NEXT STUDIO",meeting:"NEXT MEETING",recording:"NEXT RECORDING",other:"NEXT EVENT"};
let state=loadState();let activeFilter="all";
function loadState(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));if(saved&&Array.isArray(saved.schedules))return saved}catch(e){console.warn(e)}return{schedules:[{id:crypto.randomUUID(),type:"studio",title:"スタジオ練習",date:"2026-07-24",time:"20:00",place:"熊本市内スタジオ",quota:0,memo:"新曲確認"},{id:crypto.randomUUID(),type:"live",title:"熊本 Be-9 ライブ",date:"2026-08-02",time:"18:00",place:"KUMAMOTO Be-9",quota:20000,memo:"集合15:00"}]}}
function persist(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));renderAll()}
function byId(id){return document.getElementById(id)}
function escapeHtml(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"})[c])}
function eventDate(i){return new Date(`${i.date}T${i.time||"00:00"}:00`)}
function sortedSchedules(){return[...state.schedules].sort((a,b)=>eventDate(a)-eventDate(b))}
function futureSchedules(){const now=new Date();return sortedSchedules().filter(i=>eventDate(i)>=now)}
function formatYen(v){return new Intl.NumberFormat("ja-JP",{style:"currency",currency:"JPY",maximumFractionDigits:0}).format(Number(v||0))}
function showPage(id){document.querySelectorAll(".page").forEach(p=>p.classList.toggle("active",p.id===id));document.querySelectorAll(".bottom-nav button").forEach(b=>b.classList.toggle("active",b.dataset.page===id));scrollTo(0,0)}
document.querySelectorAll("[data-page]").forEach(b=>b.addEventListener("click",()=>showPage(b.dataset.page)));
document.querySelectorAll("[data-filter]").forEach(b=>b.addEventListener("click",()=>{activeFilter=b.dataset.filter;document.querySelectorAll("[data-filter]").forEach(x=>x.classList.toggle("active",x===b));renderScheduleList()}));
function renderHome(){const n=futureSchedules()[0];if(!n){byId("nextType").textContent="NEXT EVENT";byId("nextTitle").textContent="予定を登録してください";byId("nextMeta").textContent="スケジュール画面の「＋」から追加できます。";byId("countdown").textContent="LET'S GO!"}else{byId("nextType").textContent=typeStickers[n.type]||"NEXT EVENT";byId("nextTitle").textContent=n.title;byId("nextMeta").textContent=`${n.date} ${n.time||""} / ${n.place||"場所未定"}`;const t=new Date();t.setHours(0,0,0,0);const target=new Date(`${n.date}T00:00:00`);const diff=Math.ceil((target-t)/86400000);byId("countdown").textContent=diff>0?`あと ${diff} 日！`:diff===0?"今日！":"開催済み"}byId("scheduleCount").textContent=state.schedules.length;byId("liveCount").textContent=state.schedules.filter(i=>i.type==="live").length;byId("studioCount").textContent=state.schedules.filter(i=>i.type==="studio").length}
function renderScheduleList(){const items=sortedSchedules().filter(i=>activeFilter==="all"||i.type===activeFilter);const list=byId("scheduleList");if(!items.length){list.innerHTML='<article class="panel">該当する予定はありません。</article>';return}list.innerHTML=items.map(i=>`<article class="item ${i.type}"><div class="item-head"><div><h3>${escapeHtml(i.title)}</h3><p>${escapeHtml(i.date)} ${escapeHtml(i.time||"")}</p></div><span class="badge">${escapeHtml(typeNames[i.type]||"その他")}</span></div><p>📍 ${escapeHtml(i.place||"場所未定")}</p>${Number(i.quota||0)>0?`<span class="quota">ノルマ ${formatYen(i.quota)}</span>`:""}${i.memo?`<p>📝 ${escapeHtml(i.memo)}</p>`:""}<div class="row-actions"><button onclick="editSchedule('${i.id}')">編集</button><button class="danger" onclick="deleteSchedule('${i.id}')">削除</button></div></article>`).join("")}
function renderAll(){renderHome();renderScheduleList()}
const dialog=byId("scheduleDialog"),form=byId("scheduleForm");
byId("addSchedule").addEventListener("click",()=>{form.reset();byId("scheduleId").value="";byId("scheduleType").value="live";byId("dialogTitle").textContent="予定を追加";dialog.showModal()});
byId("cancelSchedule").addEventListener("click",()=>dialog.close());
form.addEventListener("submit",e=>{e.preventDefault();const id=byId("scheduleId").value;const data={type:byId("scheduleType").value,title:byId("scheduleTitle").value.trim(),date:byId("scheduleDate").value,time:byId("scheduleTime").value,place:byId("schedulePlace").value.trim(),quota:Number(byId("scheduleQuota").value||0),memo:byId("scheduleMemo").value.trim()};if(!data.title||!data.date){alert("タイトルと日付を入力してください。");return}if(id){const target=state.schedules.find(i=>i.id===id);if(target)Object.assign(target,data)}else state.schedules.push({id:crypto.randomUUID(),...data});dialog.close();persist()});
window.editSchedule=id=>{const i=state.schedules.find(x=>x.id===id);if(!i)return;byId("dialogTitle").textContent="予定を編集";byId("scheduleId").value=i.id;byId("scheduleType").value=i.type;byId("scheduleTitle").value=i.title;byId("scheduleDate").value=i.date;byId("scheduleTime").value=i.time||"";byId("schedulePlace").value=i.place||"";byId("scheduleQuota").value=Number(i.quota||0)||"";byId("scheduleMemo").value=i.memo||"";dialog.showModal()};
window.deleteSchedule=id=>{const i=state.schedules.find(x=>x.id===id);if(i&&confirm(`「${i.title}」を削除しますか？`)){state.schedules=state.schedules.filter(x=>x.id!==id);persist()}};
let deferredPrompt=null;window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e});byId("installBtn").addEventListener("click",async()=>{if(!deferredPrompt){alert("ブラウザのメニューから「ホーム画面に追加」を選択してください。");return}deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null});
renderAll();
